version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_agenda
    environment:
      POSTGRES_DB: usuarios_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d usuarios_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  usuario-service:
    build: .
    container_name: usuario-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usuarios_db
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

volumes:
  postgres_data:
